### ISSUE TITLE
Error Crash

### ISSUE THREAD

**Issue by vpttyn** [HunteRoi/discord-temp-channels#14]
{
    "time": 1697130405770,
    "stack": "TypeError: Cannot read properties of null (reading 'shift')\n    at C:\\Users\\Administrator\\Desktop\\Raze\\node_modules\\@hunteroi\\discord-temp-channels\\lib\\TempChannelsManager.js:150:110\n    at Array.map (<anonymous>)\n    at #createNewChild (C:\\Users\\Administrator\\Desktop\\Raze\\node_modules\\@hunteroi\\discord-temp-channels\\lib\\TempChannelsManager.js:150:54)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Client.<anonymous> (C:\\Users\\Administrator\\Desktop\\Raze\\node_modules\\@hunteroi\\discord-temp-channels\\lib\\TempChannelsManager.js:74:71)",
    "message": "Cannot read properties of null (reading 'shift')"
}

**Comment by HunteRoi** [comment]
Hello :smile: do you happen to create voice channels without numbering them?
If so, it appears that [this specific line](https://github.com/HunteRoi/discord-temp-channels/blob/fe22dbddb2da70786dd0ea8a2d8cecd9d8ad994d/src/TempChannelsManager.ts#L165) is throwing an error because no voice channels satisfy the regex condition.

**Comment by HunteRoi** [comment]
I might look into adapting this code a little bit to prevent the library to throw exceptions at random like that but I highly suggest that you consider numbering your dynamic channels. The entire manager stands on dynamic channels discovery to manage them. If they don't have a pattern in the config to fit for recognition, many features won't work properly.

**Comment by HunteRoi** [comment]
Fixed by #15
